POST http://localhost:8000/v2/auth/token

Content-Type: application/json
{
  "userid": "client@gmail.com",
  "password": "12345678",
  "grantType": "client_account"
}

####
POST http://localhost:3200/auth/seed_user

Content-Type: application/json
{
  "userid": "client@gmail.com",
  "password": "12345678",
  "grantType": "client_account"
}
